import User from './models/User.js';
import Category from './models/Category.js';
import Product from './models/Product.js';

const BASE_IMG = 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/04/';

const PRODUCTS_DATA = [
  // ── TAPS ──────────────────────────────────────────────────────────────────
  {
    name: 'Push Button Tap',
    slug: 'push-button-tap',
    description: 'Australian-made push button tap for drums and containers. Easy one-handed operation, suitable for IBC tanks and barrels.',
    price: 6.50,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + '04-1.jpg', alt: 'Push Button Tap' }],
    stock: 500,
    sku: 'TAP-001',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.5,
    reviewCount: 42,
    tags: ['tap', 'push button', 'drum tap'],
  },
  {
    name: 'Snap Tap – 3/4″ BSP',
    slug: 'snap-tap-3-4-bsp',
    description: 'Standard 3/4" BSP snap tap. Fits all standard BSP threaded drums and containers. Quick snap-fit design for easy installation.',
    price: 6.50,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'SNAP-TAP-%E2%80%93-LARGE.jpg', alt: 'Snap Tap 3/4 BSP' }],
    stock: 800,
    sku: 'TAP-002',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 87,
    tags: ['snap tap', 'bsp', '3/4 inch', 'drum tap'],
  },
  {
    name: 'Snap Tap – Standard Thread 3/4″ UNF',
    slug: 'snap-tap-standard-thread-3-4-unf',
    description: 'Snap tap with standard 3/4" UNF thread. Ideal for drums and containers with UNF thread fittings.',
    price: 6.50,
    categorySlug: 'taps',
    images: [{ url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img4.jpg', alt: 'Snap Tap UNF' }],
    stock: 400,
    sku: 'TAP-003',
    rating: 4.5,
    reviewCount: 29,
    tags: ['snap tap', 'unf', 'drum tap'],
  },
  {
    name: 'Snap Tap – Female Thread 3/8″ BSP',
    slug: 'snap-tap-female-thread-3-8-bsp',
    description: 'Snap tap with female 3/8" BSP thread. Suitable for smaller containers and fittings requiring a 3/8" BSP connection.',
    price: 6.50,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'SNAP-TAP-%E2%80%93-FEMALE.jpg', alt: 'Snap Tap Female 3/8 BSP' }],
    stock: 350,
    sku: 'TAP-004',
    rating: 4.4,
    reviewCount: 18,
    tags: ['snap tap', 'female thread', '3/8 bsp'],
  },
  {
    name: 'Snap Tap – 44mm Long Thread',
    slug: 'snap-tap-44mm-long-thread',
    description: 'Snap tap with 44mm long thread for thick-walled containers and drums requiring extra thread depth.',
    price: 6.50,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'A-Tap-600x292-1.jpg', alt: 'Snap Tap 44mm Long Thread' }],
    stock: 300,
    sku: 'TAP-005',
    rating: 4.5,
    reviewCount: 22,
    tags: ['snap tap', 'long thread', '44mm'],
  },
  {
    name: 'Snap Tap – Box of 25, 3/4″ BSP',
    slug: 'snap-tap-box-of-25-3-4-bsp',
    description: 'Value pack of 25 x 3/4" BSP snap taps. Perfect for trade buyers and bulk orders. Great savings over individual pricing.',
    price: 85.25,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'SNAP-TAP-%E2%80%93-BOX.jpg', alt: 'Snap Tap Box of 25' }],
    stock: 100,
    sku: 'TAP-006',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 31,
    tags: ['snap tap', 'bulk', 'box', 'trade'],
  },
  {
    name: '3/4″ BSP Snap Tap (Header Card)',
    slug: '3-4-bsp-snap-tap-header-card',
    description: 'Retail-packaged 3/4" BSP snap tap on a header card, ready for display. Ideal for retail and hardware stores.',
    price: 6.80,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'HEADER-CARDS.jpg', alt: 'Snap Tap Header Card' }],
    stock: 200,
    sku: 'TAP-007',
    rating: 4.5,
    reviewCount: 14,
    tags: ['snap tap', 'retail', 'header card'],
  },
  {
    name: 'Snap Tap Gold Plated',
    slug: 'snap-tap-gold-plated',
    description: 'Premium gold-plated snap tap for decorative and premium applications. Corrosion-resistant finish.',
    price: 16.90,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'SNAP-TAP-GOLD-PLATED25-1.jpg', alt: 'Snap Tap Gold Plated' }],
    stock: 150,
    sku: 'TAP-008',
    rating: 4.7,
    reviewCount: 19,
    tags: ['snap tap', 'gold', 'premium', 'plated'],
  },
  {
    name: 'Snap Tap Chrome Plated',
    slug: 'snap-tap-chrome-plated',
    description: 'Chrome-plated snap tap for a premium polished finish. Excellent corrosion resistance for long-lasting performance.',
    price: 0.00,
    categorySlug: 'taps',
    images: [{ url: BASE_IMG + 'SNAP-TAP-CHROME-PLATED.jpg', alt: 'Snap Tap Chrome Plated' }],
    stock: 100,
    sku: 'TAP-009',
    rating: 4.6,
    reviewCount: 11,
    tags: ['snap tap', 'chrome', 'plated'],
  },

  // ── BSP FITTINGS ──────────────────────────────────────────────────────────
  {
    name: 'BSP Adaptor',
    slug: 'bsp-adaptor',
    description: 'Australian-made BSP adaptor for connecting BSP fittings. Durable polyethylene construction for long service life.',
    price: 6.30,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'BSP-ADAPTOR.jpg', alt: 'BSP Adaptor' }],
    stock: 600,
    sku: 'BSP-001',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.7,
    reviewCount: 54,
    tags: ['bsp', 'adaptor', 'fitting'],
  },
  {
    name: 'BSP Adaptor Washer Set',
    slug: 'bsp-adaptor-washer-set',
    description: 'Complete BSP adaptor and washer set for a leak-free seal. Includes adaptor and matching washer.',
    price: 6.70,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'BSP-ADAPTOR-WASHER-SET-1.jpg', alt: 'BSP Adaptor Washer Set' }],
    stock: 500,
    sku: 'BSP-002',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 38,
    tags: ['bsp', 'adaptor', 'washer', 'set'],
  },
  {
    name: 'BSP Washer',
    slug: 'bsp-washer',
    description: 'High-quality polyethylene BSP washer. Provides a reliable seal for all BSP fittings and adaptors.',
    price: 0.60,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'BSP-WASHER.jpg', alt: 'BSP Washer' }],
    stock: 2000,
    sku: 'BSP-003',
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 72,
    tags: ['bsp', 'washer', 'seal'],
  },
  {
    name: 'BSP Bung Cap',
    slug: 'bsp-bung-cap',
    description: 'BSP bung cap for sealing drum and container openings. Prevents leaks and contamination during storage and transport.',
    price: 0.75,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'BSP-BUNG-2.jpg', alt: 'BSP Bung Cap' }],
    stock: 1500,
    sku: 'BSP-004',
    rating: 4.5,
    reviewCount: 45,
    tags: ['bsp', 'bung', 'cap', 'seal'],
  },
  {
    name: 'Camlock Adaptor',
    slug: 'camlock-adaptor',
    description: 'Camlock adaptor for quick-connect coupling systems. Widely used in industrial and agricultural applications.',
    price: 6.50,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'CAMLOCK-ADAPTOR-1.jpg', alt: 'Camlock Adaptor' }],
    stock: 400,
    sku: 'BSP-005',
    isFeatured: true,
    rating: 4.7,
    reviewCount: 33,
    tags: ['camlock', 'adaptor', 'coupling'],
  },
  {
    name: 'Camlock Bung Cap',
    slug: 'camlock-bung-cap',
    description: 'Camlock bung cap for sealing camlock fittings and drum openings. Secure and leak-proof design.',
    price: 0.45,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'CAMLOCK-CAP-1.jpg', alt: 'Camlock Bung Cap' }],
    stock: 1800,
    sku: 'BSP-006',
    rating: 4.5,
    reviewCount: 28,
    tags: ['camlock', 'bung', 'cap'],
  },
  {
    name: 'Camlock Washer',
    slug: 'camlock-washer',
    description: 'Replacement washer for camlock fittings. Ensures a tight, leak-free connection in all camlock coupling systems.',
    price: 0.60,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'CAMLOCK-WASHER.jpg', alt: 'Camlock Washer' }],
    stock: 2000,
    sku: 'BSP-007',
    rating: 4.6,
    reviewCount: 41,
    tags: ['camlock', 'washer'],
  },
  {
    name: 'Camlock Adaptor, Cap and Washer Set',
    slug: 'camlock-adaptor-cap-and-washer-set',
    description: 'Complete camlock set including adaptor, bung cap, and washer. Everything you need for a full camlock installation.',
    price: 6.95,
    categorySlug: 'bsp-fittings',
    images: [{ url: BASE_IMG + 'CAMLOCK-ADAPTOR-CAP-AND-WASHER-SET-3.jpg', alt: 'Camlock Adaptor Cap Washer Set' }],
    stock: 350,
    sku: 'BSP-008',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 57,
    tags: ['camlock', 'set', 'adaptor', 'washer'],
  },

  // ── CONTAINERS ────────────────────────────────────────────────────────────
  {
    name: '54 Litre Industrial Bin Only',
    slug: '54-litre-industrial-bin-only',
    description: '54-litre heavy-duty industrial bin. Robust HDPE construction for industrial and commercial waste collection and storage.',
    price: 18.00,
    categorySlug: 'containers',
    images: [{ url: BASE_IMG + '54-LITRE-BIN.jpg', alt: '54 Litre Industrial Bin' }],
    stock: 200,
    sku: 'CON-001',
    isFeatured: true,
    rating: 4.6,
    reviewCount: 24,
    tags: ['bin', 'industrial', '54 litre', 'container'],
  },
  {
    name: '44 Litre Industrial Bin & Lid',
    slug: '44-litre-industrial-bin-and-lid',
    description: '44-litre industrial bin complete with lid. Ideal for workshops, factories, and commercial settings. Durable and stackable.',
    price: 22.00,
    categorySlug: 'containers',
    images: [{ url: BASE_IMG + '44-LITRE-BIN.jpg', alt: '44 Litre Industrial Bin and Lid' }],
    stock: 180,
    sku: 'CON-002',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    reviewCount: 36,
    tags: ['bin', 'industrial', '44 litre', 'lid', 'container'],
  },
  {
    name: 'Handy Case',
    slug: 'handy-case',
    description: 'Compact and durable handy case for storing small parts and accessories. Lightweight and easy to carry.',
    price: 2.85,
    categorySlug: 'containers',
    images: [{ url: BASE_IMG + 'handy-case-1.png', alt: 'Handy Case' }],
    stock: 400,
    sku: 'CON-003',
    rating: 4.4,
    reviewCount: 17,
    tags: ['case', 'storage', 'small parts'],
  },

  // ── POURERS ───────────────────────────────────────────────────────────────
  {
    name: 'Pourers',
    slug: 'pourers',
    description: 'High-quality plastic pourers for bottles and containers. Provides a controlled, drip-free pour for liquids.',
    price: 7.30,
    categorySlug: 'pourers',
    images: [{ url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/POURERS-2.jpg', alt: 'Pourers' }],
    stock: 600,
    sku: 'POU-001',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.6,
    reviewCount: 48,
    tags: ['pourer', 'bottle', 'dispenser'],
  },

  // ── HOME BREW PRODUCTS ────────────────────────────────────────────────────
  {
    name: 'Bottle Draining Tree',
    slug: 'bottle-draining-tree',
    description: 'Essential bottle draining tree for home brewers. Holds up to 45 bottles upside down for draining and drying after washing.',
    price: 31.79,
    categorySlug: 'home-brew-products',
    images: [{ url: BASE_IMG + 'BOTTLE-DRAINING-TREE-2-1.jpg', alt: 'Bottle Draining Tree' }],
    stock: 120,
    sku: 'HB-001',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 63,
    tags: ['home brew', 'bottle draining', 'brewing equipment'],
  },

  // ── SPECIAL PRODUCTS (AUSSIE TURBO RIPPER) ────────────────────────────────
  {
    name: 'Straight Shaft Whipper Snipper Head',
    slug: 'straight-shaft-whipper-snipper-head',
    description: 'Aussie Turbo Ripper straight shaft whipper snipper head. Fits most standard straight shaft trimmers. Australian made for Australian conditions.',
    price: 60.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'STRAIGHT-SHAFT-HEADS-1.jpg', alt: 'Straight Shaft Whipper Snipper Head' }],
    stock: 80,
    sku: 'ATR-001',
    isFeatured: true,
    rating: 4.7,
    reviewCount: 39,
    tags: ['whipper snipper', 'trimmer head', 'straight shaft', 'aussie turbo ripper'],
  },
  {
    name: 'Bent Shaft Whipper Snipper Head',
    slug: 'bent-shaft-whipper-snipper-head',
    description: 'Aussie Turbo Ripper bent shaft whipper snipper head. Designed for bent shaft trimmers with heavy-duty cutting performance.',
    price: 60.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'BENT-SHAFT-2.jpg', alt: 'Bent Shaft Whipper Snipper Head' }],
    stock: 80,
    sku: 'ATR-002',
    isFeatured: true,
    rating: 4.7,
    reviewCount: 35,
    tags: ['whipper snipper', 'trimmer head', 'bent shaft', 'aussie turbo ripper'],
  },
  {
    name: 'Metal (Aluminium) Whipper Snipper Head',
    slug: 'metal-aluminium-whipper-snipper-head',
    description: 'Heavy-duty aluminium Aussie Turbo Ripper whipper snipper head. Superior strength and durability for professional use.',
    price: 120.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'METAL-HEAD.jpg', alt: 'Metal Aluminium Whipper Snipper Head' }],
    stock: 50,
    sku: 'ATR-003',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 28,
    tags: ['whipper snipper', 'aluminium', 'metal head', 'professional'],
  },
  {
    name: 'Clip and Tube',
    slug: 'clip-and-tube',
    description: 'Replacement clip and tube set for the Aussie Turbo Ripper trimmer head. Keeps your cutting cord loaded and ready.',
    price: 10.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'CLIP-AND-TUBE.jpg', alt: 'Clip and Tube' }],
    stock: 200,
    sku: 'ATR-004',
    rating: 4.5,
    reviewCount: 22,
    tags: ['clip', 'tube', 'trimmer', 'replacement part'],
  },
  {
    name: 'Star Cord (Trimming Cord) 1KG',
    slug: 'star-cord-trimming-cord-1kg',
    description: '1kg spool of star cord trimming line for whipper snippers. Heavy-duty star-profile design for clean, efficient cutting.',
    price: 80.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'TRI-CORD-350-X350.jpg', alt: 'Star Cord 1KG' }],
    stock: 100,
    sku: 'ATR-005',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 47,
    tags: ['trimming cord', 'star cord', '1kg', 'whipper snipper'],
  },
  {
    name: 'Star Cord (Trimming Cord) Bundles',
    slug: 'star-cord-trimming-cord-bundles',
    description: 'Pre-cut bundle packs of star trimming cord. Convenient size for quick loading into the Aussie Turbo Ripper head.',
    price: 22.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'TRI-CORD-BUNDLES-1.jpg', alt: 'Star Cord Bundles' }],
    stock: 200,
    sku: 'ATR-006',
    rating: 4.7,
    reviewCount: 31,
    tags: ['trimming cord', 'star cord', 'bundles'],
  },
  {
    name: 'Clip and Tube with 25 Star Cord',
    slug: 'clip-and-tube-with-25-star-cord',
    description: 'Clip and tube kit including 25 pre-cut star cord pieces. Ready-to-use kit for the Aussie Turbo Ripper trimmer head.',
    price: 25.00,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'CLIP-AND-TUBE-WITH-25-TRI-CORD-1-1.jpg', alt: 'Clip and Tube with 25 Star Cord' }],
    stock: 150,
    sku: 'ATR-007',
    rating: 4.8,
    reviewCount: 26,
    tags: ['clip', 'tube', 'star cord', 'kit'],
  },
  {
    name: 'Straight Shaft Heads + Clip & Tube with 25 Tri Cords',
    slug: 'straight-shaft-heads-clip-tube-with-25-tri-cords',
    description: 'Complete straight shaft starter kit: Aussie Turbo Ripper head, clip and tube, plus 25 star cord pieces. Everything you need to get started.',
    price: 49.95,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'STRAIGHT-SHAFT-HEADS-1.jpg', alt: 'Straight Shaft Starter Kit' }],
    stock: 60,
    sku: 'ATR-008',
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    reviewCount: 44,
    tags: ['starter kit', 'straight shaft', 'trimmer', 'bundle'],
  },
  {
    name: 'Bent Shaft + Clip & Tube with 25 Tri Cords',
    slug: 'bent-shaft-clip-tube-with-25-tri-cords',
    description: 'Complete bent shaft starter kit: Aussie Turbo Ripper head, clip and tube, plus 25 star cord pieces. Best value package.',
    price: 49.95,
    categorySlug: 'special-products',
    images: [{ url: BASE_IMG + 'BENT-SHAFT.jpg', alt: 'Bent Shaft Starter Kit' }],
    stock: 60,
    sku: 'ATR-009',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 38,
    tags: ['starter kit', 'bent shaft', 'trimmer', 'bundle'],
  },
];

export const seedAdmin = async () => {
  const exists = await User.findOne({ role: 'admin' });
  if (exists) return;

  await User.create({
    name: 'Admin',
    email: process.env.ADMIN_EMAIL,
    password: process.env.ADMIN_PASSWORD,
    role: 'admin',
  });
  console.log('Admin user seeded');

  const categoriesData = [
    {
      name: 'BSP Fittings',
      slug: 'bsp-fittings',
      description: 'Australian-made BSP fittings, adaptors, washers, bung caps and camlock components.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img2.jpg', alt: 'BSP Fittings' },
      productCount: 8,
      order: 1,
    },
    {
      name: 'Containers',
      slug: 'containers',
      description: 'Industrial bins and storage containers for commercial and industrial use.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img1.jpg', alt: 'Containers' },
      productCount: 3,
      order: 2,
    },
    {
      name: 'Home Brew Products',
      slug: 'home-brew-products',
      description: 'Everything you need for home brewing — bottle draining trees and more.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img3.jpg', alt: 'Home Brew Products' },
      productCount: 1,
      order: 3,
    },
    {
      name: 'Taps',
      slug: 'taps',
      description: 'Snap taps, push button taps and drum taps for BSP and UNF threaded containers.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img4.jpg', alt: 'Taps' },
      productCount: 9,
      order: 4,
    },
    {
      name: 'Pourers',
      slug: 'pourers',
      description: 'Bottle pourers for controlled, drip-free dispensing of liquids.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/POURERS-2-1.jpg', alt: 'Pourers' },
      productCount: 1,
      order: 5,
    },
    {
      name: 'Special Products',
      slug: 'special-products',
      description: 'Aussie Turbo Ripper whipper snipper heads, trimming cord and accessories.',
      image: { url: 'https://www.beneficialplastics.com.au/wp-content/uploads/2020/03/categori_img6.jpg', alt: 'Special Products' },
      productCount: 9,
      order: 6,
    },
  ];

  const categories = await Category.insertMany(categoriesData);
  const catMap = Object.fromEntries(categories.map((c) => [c.slug, c._id]));

  const products = PRODUCTS_DATA.map(({ categorySlug, ...p }) => ({
    ...p,
    category: catMap[categorySlug],
    isActive: true,
  }));

  await Product.insertMany(products);
  console.log(`Seeded ${products.length} products across ${categories.length} categories`);
};
